# Generated by Django 2.1.4 on 2018-12-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
