version: 2

jobs:
  build_server_prod:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:11.1-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd server
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            cd server
            . venv/bin/activate
            python manage.py test
      - deploy:
          name: Deploy server to AWS
          command: |
            cd server
            . venv/bin/activate
            sh deploy/deploy.sh

  build_client_prod:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.6-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd frontend
            npm install
      - deploy:
          name: Build bundle and deploy to S3.
          command: |
            cd frontend
            sh deploy/deploy.sh


workflows:
  version: 2
  full_deploy:
    jobs:
      - build_server_prod:
          filters:
            branches:
              only: master
      - build_client_prod:
          requires:
            - build_server_prod
