# Generated by Django 2.1.4 on 2019-01-11 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_orgs_and_orgs_column_on_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.AddField(
            model_name='userorganization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together={('user', 'organization')},
        ),
    ]
