# Generated by Django 2.1.4 on 2019-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_user_organization_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
