# Generated by Django 2.1.4 on 2019-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_last_active_at_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
