# Generated by Django 2.1.4 on 2019-01-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grip',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
