# Generated by Django 2.1.4 on 2019-01-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grips', '0002_add_deleted_to_grip'),
    ]

    operations = [
        migrations.AddField(
            model_name='grip',
            name='owned_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
