# Generated by Django 2.1.4 on 2019-01-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grips', '0003_add_owned_by_to_grip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(db_index=True, max_length=254)),
                ('is_pinned', models.BooleanField(default=False)),
                ('has_voted', models.BooleanField(default=False)),
                ('grip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grips.Grip')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usergrip',
            unique_together={('user', 'grip')},
        ),
    ]
