# Generated by Django 2.1.4 on 2019-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grips', '0005_add_source_to_grip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grip',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
